### PR TITLE
591 plot ts control

### PR DESCRIPTION
**Pull request by richardsc**
This PR is to address #591 . I have created the PR from the branch that @dankelley created to address this, but it is a LOT of changes (and GH says that it "can't automatically merge", so I'm going to leave this for @dankelley to view/merge.

### CODE REVIEW

**Comment by richardsc** [comment]
This languished for some time, due to some merge conflicts that I think arose from the package down website. I've manually resolved them (mostly they were just for things like dates in the HTML files) and merged. I hope I didn't mess anything up.

It seems as though @dankelley is still not getting notifcations from Github??

**Comment by dankelley** [comment]
Actually, I am getting notifications again.  I have no idea why it started again, but I won't complain!

I just pulled "develop" and it builds OK and tests OK.  I will next run the check, and then I will run spell-check and then url-check and then I'll rebuild the website.  If problems arise in any of these things, I'll fix them, but I won't bother reopening the issue.

**Comment by dankelley** [comment]
Spell-check reveals as follows.  I'll fix and move to next check.
```
drawByCycle   plot-argoFloats-method.Rd:143
lwd           plot-argoFloats-method.Rd:143
ORCID         argoFloats.Rd:73,77,82,83
RStudio       README.md:15,17,19,21
              README.Rmd:25,26,27,28
TEOS          plotArgoTS.Rd:47
TSControl     plot-argoFloats-method.Rd:143
```

**Comment by dankelley** [comment]
URL checker has problems.  I will fix.

```
> urlchecker::url_check()
! Warning: man/argoFloats.Rd:82:72 Moved
  \item Dewey Dunnington \email{dewey.dunnington@dfo-mpo.gc.ca} (\href{http://orcid.org/0000-0002-9415-4582}{ORCID}) [contributor]
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                       https://orcid.org/0000-0002-9415-4582
```

**Comment by dankelley** [comment]
FYI to other developers: what I'm doing is to manually run the lines in `check_package.R`.  I do it manually so I can make a fix and rebuild for each problem I see. I do this step by step because the success of some things (like the remote builds) are not ensured by this script, as they are run asynchronously.

**Comment by dankelley** [comment]
I got all-clear for all the tests in `check_package.R` so I also rebuilt the online docs.  Thus, I see no other action to be taken here.

**Pull request merged**
