### PR TITLE
Issue209 new

### PR DESCRIPTION
**Pull request by j-harbin**
Hi @dankelley,

Instead of merging this directly into develop myself, I thought I would make a pull request, although more work for you :), because a lot of changes have been made:

1. The code we have created together (thank you for the help)
2. The documentation for subset.R to explain the ability to subset by index and argos type as well as demonstrating an example for subset by column
3. testthat for subset by column
4. New error message, creating a new line when necessary (as discussed in the vftf yesterday)

### CODE REVIEW

**Comment by dankelley** [comment]
Since "develop" just got pushed to (for #214), can you merge "develop" into your branch and then re-submit the pull request?  That might save me some time.  (I realize I am breaking etiquette, because you likely did a merge a few moments before your pull request, but I updated "develop" at basically the same time!)

**Comment by j-harbin** [comment]
I think I may have fixed this. Atom is a great application or this because it colour codes the conflicts. Please let me know if it works on your end as well.

**Comment by dankelley** [comment]
The github interface told me that this merged with no problem.

**Comment by dankelley** [comment]
There's still some development-stage printing that should be removed as in the snapshot below.  I recommend you fix this in "develop", so we can consider this PR to be done.

Screen Shot 2020-08-19 at 8 15 17 AM

**Pull request merged**
